### ISSUE TITLE
PSUGH PowerShell Usergroup Hannover Newsletter

### ISSUE THREAD

**Issue by StreamingKarl** [PSUGH/PowerShell#1]
Wo kann ich euren Newsletter abonnieren?
Er wird auf [https://www.netz-weise-it.training/usergroups.html](https://www.netz-weise-it.training/usergroups.html) erwähnt, aber ich finde kein Formular (auch mit deaktiviertem uBlock origin). 🧐
Thanks!

**Comment by eilissadh** [comment]
Das habe ich gefunden: [https://us11.mailchimp.com/mctx/clicks?url=http%3A%2F%2Fnetz-weise.us11.list-manage.com%2Fsubscribe%3Fu%3Dca2d2d103bac590715773bed8%26id%3D5d85e5c5d2&h=455f2d5620df060e701ef0f2fc01efaa71db1426e2a00a0eedf7c04a32212c8d&v=1&xid=d1f969dbba&uid=47893005&pool=&subject=PSUGH+GitHub](https://us11.mailchimp.com/mctx/clicks?url=http%3A%2F%2Fnetz-weise.us11.list-manage.com%2Fsubscribe%3Fu%3Dca2d2d103bac590715773bed8%26id%3D5d85e5c5d2&h=455f2d5620df060e701ef0f2fc01efaa71db1426e2a00a0eedf7c04a32212c8d&v=1&xid=d1f969dbba&uid=47893005&pool=&subject=PSUGH+GitHub).

**Comment by datenteiler** [comment]
Du kannst dich in den Newsletter eintragen lassen, wenn du mal bei uns reinschaust.
